### ISSUE TITLE
Convert WixComponent ancestor with HOC WixComponent

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#1059]
After a conversation with @eyaleizenberg and a bug that @naamagr raised, we should consider doing a refactor in the whole WixComponent infrastructure.
Today we use inheritance to mainly to support the dataHook mechanism.
Why is it not good:

1. WixComponent is using the lifecycle events `componentDidMount` and `componentWillUnmount`, so nasty bugs can occur when an inheriting component would want to implement one of these lifecycle events.

2. This is not the best practice in react.

The alternative solution can be to create an HOC WixComponent, and each component will do:
```
export default WixComponent(Button)
```
Or something...

Moreover, we had some bugs with the dataHook mechanism that can be solved if we plan the refactoring process properly. For example, we can't place dataHook on the ButtonLayout because it overrides its children data-hook.

Maybe we can change the `dataHook` --> `data-hook` with a new approach:
`dataHook` --> `data-{componentName}` 

FYI @eyaleizenberg @naamagr

**Comment by eyaleizenberg** [comment]
@lbelinsk I agree on both. We should avoid inheritance & we should make the `data-hook` more uniq. It will save a lot of headaches for developers.

Another point to consider here (but maybe it should be in another issue) is that we should do sanity tests using the testkit on WSR. It seems that you can have WSR's tests pass but then other projects can fail because they are using the testkit and it can't find some data-hook. When you find out about it, many other builds are now failing and you have to rush things to get a solution out.

**Comment by lbelinsk** [comment]
I thought maybe we should have some dummy form app for testkit playground. The form will have a lot of wsr components, and it will help us intercept a lot of real-life issues, because it is not just "render a single component and test it" approach.

**Comment by eyaleizenberg** [comment]
@lbelinsk Why would you need an app for that?

**Comment by lbelinsk** [comment]
The problem is that our tests are too simple, because they test only the component itself, which is ok.

Usually, the problems are being detected in a real-world use case, so having a test on a form which contains a lot of components together might help us discover those issues. Guineapig's form detected more bugs than any other app :)

**Comment by lbelinsk** [comment]
We are going with a different approach in wix-ui refactored library.
We have have `createHOC` that creates hoc instead of inheritance
