### ISSUE TITLE
Importing RichTextArea causes React injection into the bundle

### ISSUE THREAD

**Issue by skyiea** [wix/wix-style-react#1283]
### Summary:
Importing `RichTextArea` from WSR causes `react` & `react-dom` packages to get bundled, despite `externals` in *yoshi* config. Thus all the projects that are using `RichTextArea` can't benefit from `externals` option. **All BSM modules will have their own versions of `react` & `react-dom`.**

### Steps to reproduce:
 1. Open `/wsr/src/index.js`
 2. Add `export {default from RichTextArea} from './RichTextArea';`
 3. In CLI run `npx haste build --analyze`

### Expected behavior:
`react` & `react-dom` should be externalized if described in *yoshi* config's `externals`.

### Relevant Components:
`RichTextArea`

### Additional notes:
Brief investigation showed that the problem lies in *slate* package.

**Comment by shlomitc** [comment]
Looks like something people already encountered:
https://github.com/ianstormtaylor/slate/issues/1014

We use the `Html` serializer which requires `react-dom/server`:
https://github.com/wix/wix-style-react/blob/master/src/RichTextArea/htmlSerializer.js#L2

Can you try in your project to externalize `react-dom/server` as well? Not sure if it's the best solution but it might do the trick. Something like`"react-dom/server": "ReactDOMServer"`

**Comment by skyiea** [comment]
@shlomitc Externalizing `react-dom/server` did work (`react` & `react-dom` is not in the bundle), but I don't think `ReactDOMServer` is exposed as global variable when you include `react-dom`. In Business-Manager there is no global `ReactDOMServer` which might cause an error when `RichTextArea -> slate -> serializer` will try to use it?

**Comment by shlomitc** [comment]
@skyiea 
Can you please try to install the latest version of slate in your project and see if works?

**Comment by nitayneeman** [comment]
Hey,

Since WSR v6.18.0 - `RichTextArea` component is deprecated. You should migrate to [`RichTextInputArea`](https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=RichTextInputArea&full=0&addons=0&stories=1&panelRight=0) instead. 

Either way, the issue you described is fixed in `RichTextInputArea`. We now use Draft.js under the hood, which isn't based on `react-dom` at all.

So, I'm closing this issue - please feel free to reopen it if necessary.
