### ISSUE TITLE
Rich Text Area | Placeholder is present when composing character

### ISSUE THREAD

**Issue by aarnoldaas** [wix/wix-style-react#1473]
### Summary:
Languages like Japanese and Korean have characters that are composed from few key presses.
Placeholder do not disappear when composition of character starts. 

### Priority:
Normal

### Steps to reproduce:
 1. Choose Korean/Japanese input (keyboard layout) 
 2. Start typing into rich text area

### Expected behavior:
Placeholder should disappear when composition of character starts.

### Relevant Components:
Rich Text Area

Example:
<img width="861" alt="screen shot 2018-02-20 at 08 57 01" src="https://user-images.githubusercontent.com/9351975/36411166-debdaa24-161c-11e8-8dea-3ab05b5db2ba.png">

**Comment by nitayneeman** [comment]
Hey,

Since WSR v6.18.0 - `RichTextArea` component is deprecated. You should migrate to [`RichTextInputArea`](https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=RichTextInputArea&full=0&addons=0&stories=1&panelRight=0) instead. 

Either way, the issue you described is fixed in `RichTextInputArea`.

So, I'm closing this issue - please feel free to reopen it if necessary.
