### ISSUE TITLE
consuming wix-style-react results in duplicate css in bundle

### ISSUE THREAD

**Issue by argshook** [wix/wix-style-react#1628]
1. we `import styles from './styles.scss'` in components
2. `styles.scss` does `@import 'common'`

this repeats throughout many components

when consumer of wix-style-react bundles css, the content from `common.scss` appears multiple times.
it wouldn't be a problem if `common.scss` included only variables or mixins but we also have fonts in there. this means bundled css has `helvetica` defined many times.

this is a known issue, however, more investigation is needed

https://github.com/webpack-contrib/sass-loader/issues/145

**Comment by argshook** [comment]
summon @ranyitz perhaps you may have some insights

**Comment by ranyitz** [comment]
Hey @argshook, I want to help here, but I'm not sure I understand the problem.

Can you create a repro for this?

**Comment by argshook** [comment]
here's a repo https://github.com/wix-playground/wsr-issue-1628

it's fresh wix generated fullstack with wix-style-react
one component https://github.com/wix-playground/wsr-issue-1628/blob/master/src/components/App/App.js

i import `Text` and `Button` from wsr.
running `yoshi build` creates `dist/statics/app.css` where you can see `/* Fonts */` comment repeated few times (and a lot of source about fonts). this is coming from https://github.com/wix/wix-style-react/blob/master/src/common.scss#L3

i know that people often do some sort of `common.scss` or `main.scss` which is imported in other scss files many times. wix-style-react does this too. this results in a lot of repeated css

the question is whether approach for reusable scss should be different or is it webpack that could help us reduce these repetitions

**Comment by ranyitz** [comment]
@argshook I'll try to clear some smoke here.

1. `wix-style-react` is a component library that exposes React components that `import` css files, which means the consumers of the library should run a bundler (usually webpack) that will know how to handle `import '../styles.css'` statements. Yoshi runs webpack and is being used in `wix-style-react` build process, it is also the same tool that used for the build process of the consumers of `wix-style-react`.

2. On `wix-style-react` build process we transpile the `js` using babel and put it in dist, we also transpile the `scss` and put it by the `js`.

```
└── dist
  └── src
    └── button
      ├── button.js
      └── button.scss   // this is css, despite the "scss" suffix
```

3. After inspecting the generated css file (`app.css`) I've noticed that the `/* Fonts */` & `/* New swatches! */` comments are the only "real" duplicated content, and you won't see it in the minified file, so that's not a problem.

4. The other so-called duplicated content is the `@mixins` content (the fonts), which most of it is actually being generated [here](https://github.com/wix/wix-style-react/blob/e38cd6a8ddee4d67a09dcca106a35b830f3735dc/src/Typography/Typography.scss).

5. The [css-modules algorithm give a hash based on multiple parameters](https://github.com/wix/wix-style-react/issues/1243#issuecomment-352255677) which one of them is the relative path to the file, which means same classes would be duplicated by design, or by the nature of css modules.

6. gzip algorithm can greatly reduce duplicated content, and when measuring we should look at the gzipped size difference. [The way it works](http://www.gzip.org/algorithm.txt) is by finding sequences of data that are repeated, like duplicated string and putting them in a hashmap. So it will work amazingly good in these cases.

__To summary:__
This problem is caused by two things:
* The generation `css` out fo the `scss`, which gives us duplicated content due to the `@mixins`
* The css-modules algorithm that takes the same class, and give it a different name.

Anyway, I'm not sure how big this problem is in performance-land dut to gzip, and if there are easy solutions out there for it.

**Comment by argshook** [comment]
@talbenmoshe hey, perhaps you could chirp in as originally you discovered this?

does it impact your project a lot, do you see a lot of duplication?

**Comment by shlomitc** [comment]
@ranyitz - thanks for the thorough investigation.
Isn't duplicated code removed when using postcss?

**Comment by talbenmoshe** [comment]
I see each font-face defined 67 times in the non-minified version. and the css is 1MB.
Not sure how it affects the minified CSS which is about 325 kb:

https://static.parastorage.com/services/logo-builder-universal/1.350.0/app.css

if you look for this (for example) you'll find it defined 67 times:
```
@font-face {
  font-family: "HelveticaNeueW01-45Ligh";
```

**Comment by argshook** [comment]
@ranyitz how do you search? i do see it repeated in minified as well:

```
⇶ curl -sv https://static.parastorage.com/services/logo-builder-universal/1.350.0/app.min.css 2>&1 | \
  grep -io HelveticaNeueW10-45Ligh | \
  wc -l
70
```

**Comment by argshook** [comment]
right. i suppose case closed then? we rely on minifier and allisgood

**Comment by ranyitz** [comment]
@argshook I don't see any big production problem here. But if someone has an idea how to optimize the output while preserving the behaviour that would be always wonderful 😃

**Comment by argshook** [comment]
closing, since the issue is only relevant during development making it not really an issue
