### ISSUE TITLE
<TextField/> - Tooltip content and position are broken

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#1988]
### Summary:
as @mozesoron reported, the tooltip that is displayed by the TextField component is breaking line after each word.
![image](https://user-images.githubusercontent.com/6093192/42660620-75a76dee-8634-11e8-8be5-e7124eb6d83d.png)

In the [storybook](https://wix-wix-style-react.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.1%20Text%20Field&full=0&addons=0&stories=1&panelRight=0) the example works well

However, in a standalone project I reproduced it myself very easily.
I suspect Tooltip positioning is causing it but I cannot explain why it is not happening in the storybook as well

![image](https://user-images.githubusercontent.com/6093192/42662538-a5ee91a2-863a-11e8-8af5-bbe73a996a78.png)

```jsx
import {Container, Card, Row, Col} from 'wix-style-react/Grid';

import TextField from 'wix-style-react/TextField';
import Label from 'wix-style-react/Label';
import Input from 'wix-style-react/Input';

import React from 'react';
import './App.scss';

class App extends React.Component {

  render() {
    return (
      <div>
        <Container>
          <Row>
            <Col span={6}>
              <Card>
                <Card.Content>
                  <Row>
                    <Col span={6}>
                      <TextField info="editor link goes here" required>
                        <Label>some title</Label>
                        <Input value="some value"/>
                      </TextField>
                    </Col>
                  </Row>
                </Card.Content>
              </Card>
            </Col>
          </Row>
        </Container>
      </div>
    );
  }
}
```

```css
body {
  background: powderblue;
  margin: 0;
  padding: 5px;
}
```

In the new [`FormField`](https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=FormField&full=0&addons=0&stories=1&panelRight=0) component it doesn't happen, but the tooltip appears way off the position it should be.
You can also try to investigate it by adding the snippet to the grid .

```jsx
import FormField from 'wix-style-react/FormField';

........

<Row>
  <Col span={6}>
    <FormField label="some title" infoContent="oh my lord" required>
      <Input value="editor link goes here"/>
    </FormField>
  </Col>
</Row>
```

![image](https://user-images.githubusercontent.com/6093192/42662545-afa05992-863a-11e8-9d23-5a15d5cc5f41.png)

### Priority:
- [ ] Blocker
- [x] Urgent
- [ ] Normal
- [ ] Minor

### Relevant Components:
TextField, FormField, Tooltip

**Comment by yardnsm** [comment]
The bug also happens in the storybook example. Also, I couldn't reproduce the `< FormField/>` you've mentioned (it works fine for me).

As I see it, the problem is the tooltip's mount point. In `<FieldLabelAttributes/>` (used by `<TextField/>`), the `appendToParent` prop of the `<Tooltip/>` is set to `true` so the tooltip is mounted as a child of the `<FieldLabelAttributes/>` component. Since the tooltip has `position: absolute` and its positioning is relative to the root of `<FieldLabelAttributes/>`, the width of the tooltip is set to width of the `<FieldLabelAttributes/>` component (which is small, in fact its matching the width of the info icon), thus the text is breaking.

We can drop `position: relative` from `<FieldLabelAttributes/>`, but when we add a `<TextField/>` inside a grid (like you did) the becomes is a bit off:

![screen shot 2018-07-16 at 14 39 14](https://user-images.githubusercontent.com/11786506/42756720-0d629478-8906-11e8-867c-1025422be6ae.png)

Is there a reason why we're using `appendToParent` in `<TextField/>`? When setting it to `false` it works just fine (like `<FormField/>`):

![screen shot 2018-07-16 at 14 43 39](https://user-images.githubusercontent.com/11786506/42756889-a6a1549e-8906-11e8-85db-0a7339d60751.png)

**Comment by mozesoron** [comment]
@shlomitc we have updated to the new component
![screen shot 2018-07-16 at 18 29 52](https://user-images.githubusercontent.com/10268399/42767687-4b22e950-8926-11e8-9846-01cfc9b6d27a.png)
 and the tooltip looks fine
