### ISSUE TITLE
MultiSelect onChange cb is called on each document click

### ISSUE THREAD

**Issue by katmai7** [wix/wix-style-react#2105]
Hi, 
for `MultiSelect` component `onChange` cb is called every time when you anywhere on a page.

### Priority:
Normal

### Steps to reproduce:
![multiselect-outside-click](https://user-images.githubusercontent.com/3172108/43845767-6aab1150-9b35-11e8-947b-b00c112033a1.gif)

### Expected behavior:
As a variant do not call `onChange` if a component doesn't have a focus.

### Additional notes:
Where to find related code
1. Go here https://github.com/wix/wix-style-react/blob/master/src/MultiSelect/MultiSelect.js#L28
2. Then you find `hideOptions ` method https://github.com/wix/wix-style-react/blob/master/src/MultiSelect/MultiSelect.js#L23
3. Which calls `clearInput` https://github.com/wix/wix-style-react/blob/master/src/MultiSelect/MultiSelect.js#L189
4. And `clearInput` calls `onChange` callback

**Comment by shlomitc** [comment]
Thanks for reporting!
Do you think you can make a PR for that? I know this component is a bit tricky, but maybe we can go through it together.

the problem is the `MultiSelect` doesn't know the actual state of the dropdown (open/closed), so this means `InputWithOptions` should expose it. Then - `MultiSelect` will check and only then will decide if it needs to call `clearInput` or not.
