### ISSUE TITLE
<SideMenuDrill /> layout breaks on long texts

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#2106]
### Summary:
`<SideMenuDrill />` Arrow position breaks when used with long texts:
<img width="259" alt="screen_shot_2018-08-09_at_09 39 33" src="https://user-images.githubusercontent.com/1684587/43884633-4be7378c-9bbf-11e8-8484-4590178ba520.png">

### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

### Blocker:
Design guidelines don't cover situations with long texts and how it should wrap.

**Comment by hepiyellow** [comment]
@milkyfruit 
Can don't see anything broken in the attached image.

Only that the title can span over more than 1 line, and in the image, the title is limited to 1 line, and there is an ellipsis .

Is that what you want?
- To add an ellipsis and limit the title to 1 line?
- I guess the consumer should be able to choose the max line limit.

Any other long-text issues other than the title?

**Comment by argshook** [comment]
I think he's talking about "Herramientas de Marketing" and wrong arrow
position in that menu item

fyi, Domas is on vacation this week

**Comment by hepiyellow** [comment]
ok, so:

1. Add ellipsis to title
1. vertically center arrow when submenu title is multi line.

@wuwa Can you confirm?

**Comment by wuwa** [comment]
2 - vertically center arrow.
ellipsis is only for main title on top (name of site)

**Comment by hepiyellow** [comment]
@wuwa @milkyfruit 
In order to center the arrow when text is multi-line,
 I need to know what should be the spacing between the arrow (or badge) and the text.
The only clue I found in the specs (6.0 Business Manager), 
Is this container called `.Drill-In`, which is `54px` wide, and goes all the way from the right-side of the menu.
![screen shot 2018-09-02 at 14 30 32](https://user-images.githubusercontent.com/6338722/44955533-7d5b7d80-aebd-11e8-96ba-632be8b591fb.png)

So it kind of defines the border where the text should wrap.
Which makes sense, since It looks like the widest "thing" that can appear in the "Drill-in", is this Button Counter which is 24px wide:
![screen shot 2018-09-02 at 14 37 16](https://user-images.githubusercontent.com/6338722/44955551-b72c8400-aebd-11e8-9584-5b5a050dac47.png)


Can you confirm?

**Comment by hepiyellow** [comment]
@wuwa @milkyfruit 
## Adding ellipsis to title
We have the ellipsis support in the new `<Heading/>` component.
The specs show that the title is Helvetica45 with font-size 20px.
That combinations does not exist in the new Typography.

*Should it be `H2` or `H3`?*

**Comment by wuwa** [comment]
- regarding the wrapping - the suffix to the content (arrow, counterBadge, whatever) is 30px from right of sidebar. text should wrap naturally if there is no room, depending on the suffix. arrow SVG has 24px box around it already.

- title was custom made for this component (like colors etc) - you can upgrade it to be H3 (20px helvetica55).

- CONCLUSION: not sure this is worth changing right now, there is a new design coming soon for this sidebar anyway.

**Comment by hepiyellow** [comment]
@wuwa 
* should badge (orange dot) take also `24px` width ?
![screen shot 2018-09-02 at 16 40 43](https://user-images.githubusercontent.com/6338722/44956582-f7e0c900-aece-11e8-83fd-3cdffad7b5b0.png)

* We are making the change anyways.

**Comment by milkyfruit** [comment]
@hepiyellow what's the status of this issue? Is there anything I can still help with?
I think for now is enough to vertically align the arrow on the right, or whatever any other object is positioned on the right (if it's not custom made by a consumer):
![image](https://user-images.githubusercontent.com/1684587/44974380-22cb2b80-af68-11e8-8105-7d219f6bb78f.png)

![image](https://user-images.githubusercontent.com/1684587/44974350-0929e400-af68-11e8-8af8-ec646d0edc39.png)
