### ISSUE TITLE
Pasting into <MultiSelect> invokes the onSelect prop

### ISSUE THREAD

**Issue by ChenRoth** [wix/wix-style-react#2199]
### Summary:
pasting text into `<MultiSelect>` invokes the `onSelect`, which seems an unexpected behavior

### Priority:
- [x] Blocker
- [ ] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
https://codesandbox.io/s/6169w5m64r

### Expected behavior:
I would expect `onChange` to be invoked instead

### Relevant Components:
MultiSelect, InputWithOptions

**Comment by hepiyellow** [comment]
## Do we all agree?

That pasting a value should trigger automatically a "submit", (Meaning that it will try to add tags) and not leave the pasted text and wait for an "Enter" to be pressed.

**Comment by milkyfruit** [comment]
@argshook I don't recall such request. Copy/Paste functionality was never covered in the specs. "Warning" and "Error" themes were defined as manually applied skins, but not binded to any functionality.

Will do a research what are the best practices for copy/paste in tag inputs.

**Comment by milkyfruit** [comment]
Researched a bit, we can find both solutions – when "submit" is triggered when clipboard is pasted and when submit is sent only on hit "enter". You can review results [here](https://docs.google.com/spreadsheets/d/1WmYeKe4zQAIrNoYsJUVOms69uBjsTsGXbv1GrFb-iCs/edit?usp=sharing).

I would go with a submit on enter, because it gives some safety and a change to review before it's parsed.

**Comment by hepiyellow** [comment]
Resolved in release 5.24.0
