### ISSUE TITLE
<Text ellipsis /> - add ability to disable WSR <Tooltip />, use native browser tooltip instead

### ISSUE THREAD

**Issue by ipanasenko** [wix/wix-style-react#2253]
Currently it looks like this, which is not very applicable in some cases:

![image](https://user-images.githubusercontent.com/576152/45804461-d9e3d880-bcc4-11e8-99e6-2b5081b3028d.png)

What would help, is just adding `title` attribute and let browsers display native tooltip

**Comment by shlomitc** [comment]
@milkyfruit - what do you think about it?

**Comment by milkyfruit** [comment]
Maybe we could give option to toggle between Wix-Style tooltip and native tooltip?

**Comment by shlomitc** [comment]
This sounds to me like a common configuration that should be configured once and not specified (like the native browser behavior).
@milkyfruit - what should it be?

**Comment by milkyfruit** [comment]
@shlomitc Currently a tooltip appears with a slight delay due to transition animation and it has `showImmediately` property which removes that transition.
I think now, first we need to discuss with a designer who works on this app and if existing solutions suit. If a delay will be needed, maybe then we could tweak the settings of the existing prop by making `showImediately` with a quick transition, and when it's false, then it has same transition, but 2sec delay.

**Comment by ipanasenko** [comment]
@milkyfruit sorry, missed your question.
It's Media Manager G6, Nimrod Dado is the guy.

And we still need ability to display native tooltip instead of WSR Tooltip

**Comment by shlomitc** [comment]
@ipanasenko - if you're using the `<Text/>` component, the tooltip appears immediately.

**Comment by shlomitc** [comment]
but is it really needed?

**Comment by shlomitc** [comment]
currently, the design system supports the black tooltip and not the native one. I think it should stay this way in order to reduce inconsistencies.
