### ISSUE TITLE
RichTextArea: continue typing after creating a link - continues the link

### ISSUE THREAD

**Issue by zivl** [wix/wix-style-react#2332]
# Bug Report

### Relevant Components
`RichTextArea`

### Current Behavior
continues the link to the new typed in text though was not asked to

### Expected Behavior
should not continue the link when continue typing right after the link.

### Steps to Reproduce
1. add text to description field
2. click to add link
3. continue typing right after the link
https://screencast.com/t/LAS3rUkO
### Severity
- [X] Critical
- [ ] Major
- [ ] Low

**Comment by shlomitc** [comment]
@wuwa - just to verify that this is an actual bug and not an intended behavior

**Comment by wuwa** [comment]
yes, it is a bug

**Comment by nitayneeman** [comment]
Hey,

Since WSR v6.18.0 - `RichTextArea` component is deprecated. You should migrate to [`RichTextInputArea`](https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=RichTextInputArea&full=0&addons=0&stories=1&panelRight=0) instead. 

Either way, the issue you described is fixed in `RichTextInputArea`.

So, I'm closing this issue - please feel free to reopen it if necessary.
