### ISSUE TITLE
RichTextArea doesn't have a maxLength prop (aka character limitation)

### ISSUE THREAD

**Issue by gilisho** [wix/wix-style-react#2339]
# Bug Report

### Relevant Components
RichTextArea (and I think RichTextAreaComposite would be relevant too)

### Current & Expected Behavior
Currently there's not limitation on how long the input of the user is. 
We would like to have an option to add this kind of limitation, as existed in other component of WSR (such as InputArea).

### Severity
- [ ] Critical
- [ X ] Major
- [ ] Low

**Comment by wuwa** [comment]
yes, we do have specs for it. should be inner component or part of form field?

**Comment by shlomitc** [comment]
@wuwa  - part of the `FormField` component.

@gilisho - I suggest using `FormField` component instead of the `RichTextAreaComposite`
https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=FormField&full=0&addons=0&stories=1&panelRight=0

See in the docs how to use it to apply **char counter**
I'm interested in how will you calculate the number of characters? As you actually get `html` output, it is problematic to count it. Might want to transform into text.

Please tell me what is your solution so we can add it to our docs

**Comment by nitayneeman** [comment]
I'm closing this issue.
Please feel free to reopen if needed.
