### ISSUE TITLE
tooltip testkit isShown will return true for all tooltips in the tree

### ISSUE THREAD

**Issue by ehabshs** [wix/wix-style-react#2486]
# Bug Report
If i have more than one tooltip in a component, it is enough for one to be shown in order for all the others to be considered shown as well 

### Relevant Components
Tooltip

### Steps to Reproduce
consider that in my App there are two tooltips one with dataHook 'first' the other with 'second' and that both are shown and hidden on mouse enter and mouse leave
now in my test files 

const firstTooltipTestKit = tooltipTestKitFactory(wrapper, dataHook: 'first');
const secondTooltipTestKit .= tooltipTestKitFactory(wrapper, dataHook: 'second');

firstTooltipTestKit.mouseEnter();

firstTooltipTestKit.isShown() will return true as expected
secondTooltipTestKit.isShown() . will also return true or in fact any other testkit for any other Tooltip

### Severity

Major

**Comment by shlomitc** [comment]
how do you suggest solving it? a PR will be highly appreciated

**Comment by hepiyellow** [comment]
@ehabshs @shlomitc 
Actually, using the `dataHook` is a good idea.
But a small correction to the suggested implementation.

### Overview
The tooltip renders the content directly to the `document.body`.
And the driver's `isShown()` method is looking for the `tooltip` class (which is name-spaced of course).
Multiple tooltips would render content with the same `tooltip` class name.

### Solution
Instead of `isShown()` to be looking for the `tooltip` class,
it should look for a dataHook.

### TooltipContent.js

The Tooltip should render the content with a datahook
```js
data-hook={`toolip-content-${dataHook}`}
```
Where `dataHook` is the one that is passed to the `<Tooltip/>`.

### Tooltip.driver.js
The driver can take the `data-hook` from the root element, and search for `tooltip-content-????` hook.

```js
isShown: ()=> {
   const hook = element.getAttribute('data-hook');
   return !!bodyOrWrapper.querySelector(`[data-hook="tooltip-content-${hook}"]');
}
```

**Comment by hepiyellow** [comment]
@ehabshs Do you have time to make a PR?

**Comment by ehabshs** [comment]
@hepiyellow I will try tomorrow to dedicate some time, if not then i will inform you here that i won't be doing it

**Comment by ehabshs** [comment]
btw i have discovered that this is not only a problem for the isShownMethod but for the vast majority of the driver methods like hasErrorTheme, getContent. where the implementation of these methods depends on querying a global class name
