### ISSUE TITLE
RichTextArea Bug: continue typing in the middle of styled text creates styled text but doesn't mark it at toolbar

### ISSUE THREAD

**Issue by zivl** [wix/wix-style-react#2601]
# Bug Report

### Steps
1. start typing text
2. choose add styling to text in the middle
3. continue typing in the middle of styled text
4. view tool bar
### Actual Behaviour
when continue typing in a middle of styled text - type in styled text but doesn't mark it at toolbar - can't un-choose styling
Screenshot:https://screencast.com/t/iNO9JQi58
### Expected Behaviour
when typing in styled text it should be indicated in toolbar.

### Severity
Major

**Comment by nitayneeman** [comment]
Hey,

Since WSR v6.18.0 - `RichTextArea` component is deprecated. You should migrate to [`RichTextInputArea`](https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=RichTextInputArea&full=0&addons=0&stories=1&panelRight=0) instead. 

Either way, the issue you described is fixed in `RichTextInputArea`.

So, I'm closing this issue - please feel free to reopen it if necessary.
