### ISSUE TITLE
Add clickOptionWithId to DropdownLayout Driver

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#264]
Today the only way to select an option with the testkit is to select an option by it's position. It should support a selection by option id.

@nirhart

**Comment by nirhart** [comment]
The driver don't have the Ids, you can pass to it your options and then ask it to press by id, will it be useful in your opinion?

**Comment by nirhart** [comment]
Added click by value

**Comment by yaelz** [comment]
I'd like to select an option in DropdownBase by the option id. I think it's a related issue (?).

It can be implemented by using the `dropdown-item-${id}` data-hook. In my tests I used this data-hook to check if the option I wanted was rendered: https://github.com/wix-private/experts/blob/master/experts-arena/test/it/drivers/explore.driver.js#L58

**Comment by shlomitc** [comment]
can you explain why you need it?
from a user perspective (which is how you test your component), you would click based on the visual index, and not according to some meta-data.

**Comment by yaelz** [comment]
I get the ids from the server and their translation is the value. It feels
weird to pass the translation in the test, when it can change tomorrow and
make the test break. I'll share the code to make it more clear:
https://github.com/wix-private/experts/blob/master/experts-arena/test/it/Explore/languageFilter.test.js#L71
(in this code snippet I check that the options are rendered so I can click
it by index. How can I do it otherwise? I have to somehow check it was
rendered)

So - I have the language id (which I use for the option ids), from the
server, but how does the option index have to do with it? Or the options
displayed?

Thanks

**Comment by shlomitc** [comment]
translations shouldn't break your tests since we never test with actual values, but with mocked keys.
since you know the order of your options, you can simply pick according to their index (not id)

**Comment by yaelz** [comment]
Yeah, that's what I did, but the index doesn't have to do with the id I got
from the server. So the test seems not so clear to me (don't you think?)

Anyways, I can live with it, just though it could be better, and I'm
probably not the only one

**Comment by shlomitc** [comment]
I guess you have some logic regarding the ordering of the options in the list.
it can be just put the options as is, sort alphabetically, etc...
based on this logic, I guess you know what option to click on.

**Comment by shlomitc** [comment]
anyway, I would suggest not using it but would accept a PR adding the missing feature. until then, closing
