### ISSUE TITLE
`<FormField/>` - Why isn't form-field wrapping it's children with `<label/>`?

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2670]
The API required the consumer to pass the child `id` both to the child and to `<FormField/>`.
This can be avoided if we wrap the child with `<label/>`.

Is there any particular reason that we don't?

@argshook

**Comment by argshook** [comment]
I agree, but during extensive PR review i was asked to not do that, so it
is what it is now.

**Comment by xmityaz** [comment]
@argshook can you please explain the reason why you was asked this? :) 
Setting id to each field might be very frustrating. + you always need to keep it uniq for page
+ @shlomitc

**Comment by shlomitc** [comment]
Setting an id internally is problematic since it requires special treatment in you never know what id is generated on the same page by other components. Even if you generate a random number, there's still a slim chance for collisions and it also makes life harder in SSR.

That's why we never set an id internally in components.

Anyway, this is not going to be fixed soon, so I'm closing this one. thanks
