### ISSUE TITLE
<Tooltip> fails at positioning

### ISSUE THREAD

**Issue by hitpopdimestop** [wix/wix-style-react#2754]
# Bug Report

### Relevant Components
`<Tooltip />`

### Current Behavior
When we hover the icon or text tooltip sometimes appears somewhere at the bottom of the screen and then moves to the top position.

### Expected Behavior
Tooltip should appear at the expected position.

### Steps to Reproduce
I made a screencast to show the behavior:
https://drive.google.com/open?id=18Vu4ra-27728asC_vGThdqpXmJz51VLP

My code for Tooltip:
```
    <Tooltip
      content={props.typeDetails}
      theme="dark"
      appendToParent={true}
    >
      <div className={styles.icon}>
        <InfoCircle size="20px" />
      </div>
    </Tooltip>
```
And CSS (if it might be needed):
```
.icon {
  margin-left: 12px;
  position: relative;
  top: 3px;
}

.icon:hover {
  cursor: pointer;
  color: #3899ec;
}
```

### Severity
Major

**Comment by shlomitc** [comment]
Hey. it's a long time existing bug. We plan on rewriting the component to a far better implemented one where this issue and more will be fixed.

I would happily accept PRs with a possible fix if you can create one

**Comment by sidoruk-sv** [comment]
Also got into this issue: when tooltip is first-rendered it's TooltipContent has `position: absolute`, but as there is no `top/left/bottom/right` coordinates it's behaves like `position: relative`.

And there is a bug when we use tooltip with `iframe-resizer` and we got triggering resize for such case:
* video: https://take.ms/mbrHS
* wrong positioning that produce resizing: https://take.ms/4HpTa
* correct position after all styles applied: https://take.ms/KqHWa

Also you can see "blinking" of tooltip in the left corner on this storybook (hover over overflowed text):
https://my-domains.surge.sh/?selectedKind=Modals%2FConfigure%20Mailbox%20Records&selectedStory=Default&full=0&addons=0&stories=1&panelRight=0

For me it is fixed by specifying `top:0; left: -9000px;` (not to be shown in the view on "intermediate" faze), after that `react-tooltip` sets it's own `top, left` properties and tooltips shows to the user in correct position;

@mykas @shlomitc
So for now don't know where to fix - `master` branch, or in scope of #3110?

**Comment by shlomitc** [comment]
@sidoruk-sv - a fix to `master` will be great

**Comment by mykas** [comment]
Positioning is fixed also in the next generation Tooltip: https://wix-wix-style-react.surge.sh/?selectedKind=7.%20Tooltip&selectedStory=7.1%20Tooltip&full=0&addons=0&stories=1&panelRight=0
