### ISSUE TITLE
RichTextArea: unable to link selected text after unlinking

### ISSUE THREAD

**Issue by D0vydas** [wix/wix-style-react#2770]
# Bug Report

### Relevant Components
`RichTextArea`

### Steps to Reproduce
1. Select some text
1. Link it
1. Select linked text
1. Remove link

After that, text stays selected but it's impossible to link it again without reselecting.

### Severity
Major

**Comment by nitayneeman** [comment]
Hey,

Since WSR v6.18.0 - `RichTextArea` component is deprecated. You should migrate to [`RichTextInputArea`](https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=RichTextInputArea&full=0&addons=0&stories=1&panelRight=0) instead. 

Either way, the issue you described is fixed in `RichTextInputArea`.

So, I'm closing this issue - please feel free to reopen it if necessary.
