### ISSUE TITLE
RichTextArea: incorrect text is linked if it's selected from right to left

### ISSUE THREAD

**Issue by D0vydas** [wix/wix-style-react#2771]
# Bug Report

### Relevant Components
`RichTextArea`

### Steps to Reproduce
1. Select some text from right to left
1. Link it

After that, text which comes right after selection is linked.

### Severity
Major

**Comment by nitayneeman** [comment]
Hey,

Since WSR v6.18.0 - `RichTextArea` component is deprecated. You should migrate to [`RichTextInputArea`](https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=RichTextInputArea&full=0&addons=0&stories=1&panelRight=0) instead. 

Either way, the issue you described is fixed in `RichTextInputArea`.

So, I'm closing this issue - please feel free to reopen it if necessary.
