### ISSUE TITLE
Lets stop exporting defaults from JavaScript modules

### ISSUE THREAD

**Issue by mykas** [wix/wix-style-react#2787]
The intent of this issue is to agree on one way to export our JS modules.

###  Problems

Here is a list of problems on having both default and named exports ways in our library: 

*  I find it difficult to figure out what I’m importing when a module only has a default import. If you’re using a module or file you’re unfamiliar with, it can be difficult to figure out what is returned, for example:
```jsx
const Layout = require("./Layout");
import Layout from './Layout`
```
And I understand that for our users we do differently by using `import-path`, but what I am talking about is our velocity during development.
* Cli `ui-autotools` is supporting only named exports.
*  Any future `xxx-tools` will need to handle both cases.
* Worse tooling support.Speaking of IDEs, WebStorm is able to help write import statements for you. When you have finished typing an identifier that isn’t defined in the file, WebStorm will search the modules in your project to determine if the identifier is a named export in another file. At that point, it can do any of the following:

     * Underline the identifier that is missing its definition and show you the import statement that would fix it.
    * Automatically add the correct import statement (if you have enable auto import) can now automatically add an import statement based on an identifier that you type. In fact, WebStorm is able to help you a great deal when using named imports:

There is a plugin for Visual Studio Code3 that provides similar functionality. This type of functionality isn’t possible when using default exports because there is no canonical name for things you want to import.

..etc.

### Benefits

* **Fewer decisions mean faster development**. A lot of the preferences I have are for eliminating decisions during coding. Every decision you make slows you down, which is why things like coding conventions lead to faster development. I want to decide things up front and then just go.
* **Side trips slow down development**. Whenever you have to stop and look something up in the middle of coding, I call that a side trip. Side trips are sometimes necessary but there are a lot of unnecessary side trips that can slow things down. I try to write code that eliminates the need for side trips.

### Lets fix this in wix-style-react 6

lets rename all default exports to named exports on next major version so that we could have some kind of consistency.

**Comment by argshook** [comment]
> The intent of this issue is to agree on one way to export our JS modules.

as long as this is not enforced at language/compiler/transpiler level, that's never gonna happen.

we can use eslint to be that enforcer https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-default-export.md

---

> I find it difficult to figure out what I’m importing when a module only has a default ~import~ export.

are you sure? if there's only default export, you know exactly what you import, cause there's only
one thing. a bigger problem is when default and named exports are used simultaneously.

---

in TS world there's a "consensus" that named exports should be the norm (e.g. https://basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html) although i don't necessarily agree with it mainly due to:

1. named exports force consumer to use names author came up with, it becomes contract, changing it is breaking
2. naming exports somewhat enforces writing files that do more than one thing, they have tendency to grow and overkill themselves. That's not terrible but worse than doing one thing well (fun fact: if we were in strictly typed functional language, i'd say the opposite :) )

there's an interesting discussion on the topic here https://github.com/benmosher/eslint-plugin-import/issues/889 i would fall on the unpopular side there.

although i don't agree, i also don't care, it never was a problem for me. so if you really wish, we
can add the eslint rule.

**Comment by argshook** [comment]
closing, reopen for further discussion
