### ISSUE TITLE
Bug with special characters in RichTextArea

### ISSUE THREAD

**Issue by zivl** [wix/wix-style-react#2950]
# 🐛 Bug Report

### 🏗 Relevant Components
`RichTextArea`

### 😯 Current Behavior
I’m using `RichTextArea` component, and it does not support special characters such as `'`.
For example the character `'` translated to `&#x27;`

### 🤔 Expected Behavior
Support in special characters

### 👣 Steps to Reproduce

Go to WSR storybook and open `RichTextArea` playgound, press `'` and see the resulted value
https://wix-wix-style-react.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.2b%20%2B%20RichTextArea&full=0&addons=0&stories=1&panelRight=0

  - **WSR version**: `6`
  - **Yoshi version**: `3`

### 👀 Severity
Major

**Comment by shlomitc** [comment]
Hey,

Since WSR v6.18.0 - `RichTextArea` component is deprecated. You should migrate to [`RichTextInputArea`](https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=RichTextInputArea&full=0&addons=0&stories=1&panelRight=0) instead. 

Either way, the issue you described is fixed in `RichTextInputArea`. We now use Draft.js under the hood, which isn't based on `react-dom` at all.

So, I'm closing this issue - please feel free to reopen it if necessary.
