### ISSUE TITLE
<Formfield/>  - when label is placed on right side it will vertically align in center 

### ISSUE THREAD

**Issue by mykas** [wix/wix-style-react#2995]
# 🐛 Bug Report

### 🏗 Relevant Components

`<FormField/>`

### 😯 Current Behavior

![screenshot 2019-02-19 at 15 23 42](https://user-images.githubusercontent.com/8919190/53018193-63f1c200-345a-11e9-8366-2c2f11ecb045.png)

### 🤔 Expected Behavior

Defined in specs.

<img width="387" alt="screenshot 2019-02-19 at 15 21 25" src="https://user-images.githubusercontent.com/8919190/53018208-70761a80-345a-11e9-9b0a-fc00b67805c6.png">

### 👣 Steps to Reproduce

Snippet on playground:

```js
 <FormField
      infoContent="Tooltip text"
      labelPlacement="right"
      required
    >
      {({ setCharactersLeft }) => (
        <InputArea
          onChange={event => setCharactersLeft(100 - event.target.value.length)}
          placeholder="placeholder text"
          required
        />
      )}
    </FormField>
```
### 👀 Severity

-  Low

**Comment by gugu-lee** [comment]
if the form field is at the bottom of page ,the infocontent is not show.
how do it?

**Comment by gugu-lee** [comment]
but in IE,it is OK.

**Comment by gugu-lee** [comment]
if the page scrolle.the tooltip is also view at its original postion. 
in chorme .

**Comment by gugu-lee** [comment]
now i find ,if the form in Page ,has this bug.otherwise it work ok.

**Comment by gugu-lee** [comment]
in page,use fixcontent,is ok.

**Comment by argshook** [comment]
@gugu-lee hello, we're happy to help but in order to do so, please provide:

1. code example showcasing your problem (you can use [this playground](https://wix-wix-style-react.surge.sh/?selectedKind=Introduction&selectedStory=Playground&full=0&addons=0&stories=1&panelRight=0) to create one)
1. tell us actual behavior (what actually happens with example code)
1. tell us expected behavior (what you would like to happen)
