### ISSUE TITLE
testkit support

### ISSUE THREAD

**Issue by yanivefraim** [wix/wix-style-react#30]
We can use our test drivers as a testkit. 

Example:

Production code:

```js
<Button data-hook="my-button" />
```

Test:
```js
import {buttonDriverFactory} from 'wix-style-react/testkit';

const myFormWrapper = shallow(<my-form...>);

//Find your button using whatever you like (the data-hook is an option user can use to find his component on form)
const buttonComponent = myFormWrapper.findWhere(n => n.props()['data-hook'] === 'my-button');

const driver = driverFactory(buttonComponent);//driver factory should receive a component and expose an api for it. See https://github.com/wix/wix-style-react/blob/master/src/Button/Button.driver.js

driver.click();

//or

expect(driver.value()).toBe('bla');

//and so on
```

**Comment by yanivefraim** [comment]
cc @3LOK @shahata

**Comment by yanivefraim** [comment]
One thing that we should think about is private / public methods for that driver

**Comment by 3LOK** [comment]
@yanivefraim One thing we can consider is using id instead of data-hook (to be more standard).

What do you think?

**Comment by yanivefraim** [comment]
I think that this is not our concern... the user can use whatever he wants to find our component on the page and pass it to our [driverFactory](https://github.com/wix/wix-style-react/blob/master/src/Button/Button.driver.js). We also do not have to change anything on our code for that (like propagating id/data-hook etc)

**Comment by 3LOK** [comment]
Ah, gotcha. Ok, so what is src/Button.driver.js?

**Comment by yanivefraim** [comment]
We will publish it under `testkit` folder (we'll have an index.js file which will export all drivers in one place, as a testkit)

**Comment by yanivefraim** [comment]
This driver is used for internal component tests pluse acts as a testkit for host apps

**Comment by lbelinsk** [comment]
Today we have a dataHook prop which can be sent like ```<Button dataHook="myDataHook"/>```

Every component today extends WixComponent which places a data-hook on the most outer layer of the component.

@nirhart  - 

@yanivefraim  raised a good point about private / public methods for the driverFactory.
private - the methods we use only to test the component in The repo.
public - the methods we want to export for the users to use .

**Comment by hesher** [comment]
Chiming in late but - forcing the developer to pace a data hook (or any tag) on the component for the sake of using the test kit is not a great idea. 
I suggest a trade off - keep the data hook solution for users who want to use it but also, return the first match if data hook was not passed to the driver. 
That should at least allow the developer to pass a wrapper that has one component instead of placing a data hook.  

I believe the best solution is to use a predicate function to match the element, but returning the first match is good enough for users like me, who don't want to tag their components for tests.
