### ISSUE TITLE
Tooltip position is not correct when its at the edge of the screen

### ISSUE THREAD

**Issue by Jefoss** [wix/wix-style-react#300]
When the element is close to the edge of the screen, a tooltip on that element (besides the opposite side) won't be displayed properly.

**Comment by lbelinsk** [comment]
Do you mean that the tooltip should be responsive to the screen's location, right?

**Comment by Wo1v3r** [comment]
@lbelinsk  Bumping this; 
Can we talk regarding a solution and I'll try making a PR ?

**Comment by shlomitc** [comment]
Hey. Thanks for raising it again. I'll be happy for any bug fix that we find.

Here is what I think:

1. The current tooltip implementation is based on some custom positioning mechanism which works but has some bugs as you can see... Getting inside it might be difficult, but could be a fast solution.

2. Another (more ideal) solution will be using [`react-popper`](https://github.com/FezVrasta/react-popper) which is just the right solution for our use case. However, this means re-implementing large parts of the component.

3. My last option which is the one I think is the most valuable is using the [`wix-ui-core/Tooltip`](https://github.com/wix/wix-ui/blob/master/packages/wix-ui-core/src/components/Tooltip/Tooltip.tsx) component. It already uses `react-popper` and solves a lot of the issues we handled.
We also have a backoffice wrapping component styles but it offers a bit different API, so you can test it for non production usage (it can be removed any minute). If it works for you and fixes all issues - I think we can consider moving it to `wix-style-react` and use it instead of the current Tooltip implementation

**Comment by shlomitc** [comment]
a `Popover` component (using `popper.js`) was introduced in version `5.16.0`.
https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=Popover&full=0&addons=0&stories=1&panelRight=0

This component should be used as a generic mechanism to open custom popovers.
![popover-gif](https://user-images.githubusercontent.com/6093192/49974755-6e1baf80-ff43-11e8-99f6-915cd64aba81.gif)

`Tooltip`, which is a subset of this component, will be re-implemented in the future.

@Jefoss, @Wo1v3r  - do you have somewhere in your application such a use case which can be tested with the new mechanism?

**Comment by shlomitc** [comment]
Please checkout the new ‘Tooltip’ mechnism we implemented. It’s based on the same mechanism of ‘Popver’, meaning all positioning issues are fixed.
https://wix-wix-style-react.surge.sh/?selectedKind=7.%20Tooltip&selectedStory=7.1%20Tooltip&full=0&addons=0&stories=0&panelRight=0
