### ISSUE TITLE
`<Dropdown />` with dynamic width

### ISSUE THREAD

**Issue by varzager** [wix/wix-style-react#3093]
Dropdown has no option of dynamic width - to take the widest option.

desired solution would be:
add new props : `maxDropdownWidth` && `elipses={true}`(otherwise breaks line)

![image](https://user-images.githubusercontent.com/11004313/54209237-1959e780-44e6-11e9-8ed6-791c499c52fc.png)

@hepiyellow 

thanks 😃

**Comment by milkyfruit** [comment]
Thanks @varzager 

Comments from Slack WSR channel:
> Dropdown Layout's width should grow with content, but also, it should have a maximum width prop, where it stops growing. When exceeds the maximum width, then it should wrap. Ellipsis in the dropdown list isn’t good, because it would force a tooltip on top of another tooltip (dropdown list)

Link to current design specs: https://zpl.io/a87Zo6V

**Comment by varzager** [comment]
this blocks https://jira.wixpress.com/browse/EE-17505

**Comment by shlomitc** [comment]
@milkyfruit - so if I understand correctly, no action is needed here. right?
because:
1. line breaking is the expected behavior and works in the component.
2. max-width for the Dropdown is possible by wrapping with a div. not perfect but valid solution. We can just add `className` support if needed.

**Comment by milkyfruit** [comment]
@shlomitc 
1. Yes.
2. If code wise wrapping it in a div is allowed, then yes as well.

**Comment by shlomitc** [comment]
talk 1-on-1 with Guy.
The missing feature (which is described in the spec) - allow `maxWidth` for the `DropdownLayout` component, but in order to fully support it, it should also maintain the minimal width of the input container

might not be a trivial task, but agreed that it should be supported

![image](https://user-images.githubusercontent.com/6093192/54750886-e3052200-4be1-11e9-806b-a818f75010bf.png)

**Comment by milkyfruit** [comment]
Great, I will define the minimum width then as well.

**Comment by hepiyellow** [comment]
@milkyfruit 
So If I understand correctly, you allow the Options List (`<DropdownLayout/>`) to be wider than the "input container" (aka Label in the specs)? right?

If that's so, then I think it deserves a spec example.
Also:
- What if there is no room for the options-list on the right side, but it can grow to the left side? is that allowed? or should it break lines?
- I guess that in RTL, the options-list should allow growing to the left side.

**Comment by milkyfruit** [comment]
@hepiyellow in [these specs](https://zpl.io/a87Zo6V) I defined that min width is inherited from its parent/trigger:
![image](https://user-images.githubusercontent.com/1684587/54906150-57dea180-4eeb-11e9-8783-9132b3645c07.png)

When text is large, the DropdownLayout should grow both sides, unless there's no space in one of the sides. Then it grows opposite side. Technically should behave the same as [`<popover/>` element.](https://wix-wix-style-react.surge.sh/?activeTab=Usage&addons=0&full=0&panelRight=0&selectedKind=7.%20Tooltip%20and%20Popover&selectedStory=7.2%20Popover&stories=1)

**Comment by mykas** [comment]
Dropdown now support dynamicWidth when given `appendTo="window"` prop.
