### ISSUE TITLE
<Search/>: error when clearing search input 

### ISSUE THREAD

**Issue by ipanasenko** [wix/wix-style-react#3122]
Reproducible in Storybook: https://wix-wix-style-react.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.9%20Search&full=0&addons=0&stories=1&panelRight=0&activeTab=Usage

1. Enter text in search input
2. Click X icon
3. See an error:
![image](https://user-images.githubusercontent.com/576152/54548354-63444100-49b0-11e9-86f2-79ca01e69068.png)

I did small investigation and found this https://github.com/wix/wix-style-react/blob/master/src/Input/Input.js#L354 and this https://github.com/wix/wix-style-react/blob/master/src/Input/Input.js#L364

Can someone have a look and try to fix it? We see a lot of these errors in our Sentry: https://sentry.io/organizations/wix_o/issues/936631846/?project=1207945&query=is%3Aunresolved&statsPeriod=14d&utc=false

**Comment by ipanasenko** [comment]
BTW, I only see this error in production react build, somehow it's not thrown in development build

**Comment by gilmeir** [comment]
@ipanasenko can you please try the newest wix-style-react version?

Since the last version you can provide the prop `updateControlledOnClear`.
It's a flag that fixes this error.
It's a breaking change, so this behaviour will become the default only on next major version.

The breaking part is the clear button no longer clear the interval value on controlled input/search, it's up to you to do that in onClear.

Please update if it works for you.

**Comment by ipanasenko** [comment]
Works! Thanks!
