### ISSUE TITLE
<Checkbox/> - behavior on mobile web for long labels

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#3171]
# ✨ Feature Request

### 🔦 Scope
Working on mobile compatibility of the WSR components, in this case `<Checkbox/>`.

### 💁 Explanation
A question arises - when texts are long and not enough space, the checkbox should either have ellipsis or break a line.
Currently, it breaks a line, however some specs show some error case where an ellipsis is applied.

Current:
![image](https://user-images.githubusercontent.com/6093192/54951588-b0925680-4f4c-11e9-88fb-44daa213d13d.png)
Spec:
![image](https://user-images.githubusercontent.com/6093192/54951314-01ee1600-4f4c-11e9-8e31-e3e64c58aeb3.png)

### 🐾 Possible solution 
Decide wether it should be one of the above or both.

### 👀 Severity

- Major

@milkyfruit - WDYT?
@NitayRabi - CC

**Comment by milkyfruit** [comment]
If this feature is mainly for mobile, then ellipsis is not a good option, because on mobile it's hard to display a hidden text, since tooltips are not accessible on mobile.

On desktop, both options can be valid. Ellipsis we're sure don't break the layout.

I would say, we should support both options.

**Comment by shlomitc** [comment]
won't be fixed
