### ISSUE TITLE
<Rating> - new component

### ISSUE THREAD

**Issue by NitayRabi** [wix/wix-style-react#3219]
# ✨ Feature Request

### 🔦 Scope

- Create new <Rating/> component.
- @milkyfruit - have a look at [Reviews](https://zpl.io/a8pjJMx), we should create a design system equivalent.  
### 💁 Explanation

- Component should receive a numeric value to display rating (X/5).
- Component should implement onClick/onRating event.

### 👀 Severity

- Critical / Major / Low

**Comment by milkyfruit** [comment]
There are [Star](https://github.com/wix/wix-ui/blob/master/packages/wix-ui-icons-common/src/general/raw/Star.svg
) and [StarFilled](https://github.com/wix/wix-ui/blob/master/packages/wix-ui-icons-common/src/general/raw/StarFilled.svg) icons which are ideal for this purpose.
However, there's no StartHalfFilled icon yet.
Also, in order to have small icons, we need to introduce icon sizes first: https://github.com/wix/wix-style-react/issues/2639

To design a full component, I need to get a little bit more context first, I'll schedule a meeting with Nataly.

**Comment by milkyfruit** [comment]
Some updates what the component should have 
- `read-only` and `read-and-write` states
- tooltip on hover for each star
- It is allowed to rate only from 1 to 5, but results can be displayed from 1 to 10 with a half star.

**Comment by shlomitc** [comment]
Not required at the moment, so closing until specs will be created
