### ISSUE TITLE
eyes-storybook fails due to animation on component mount

### ISSUE THREAD

**Issue by gilmeir** [wix/wix-style-react#3304]
# 🐛 Bug Report

Example:
`Accordion: multiple [1024x768] - Failed 1 of 1`
Fails due to an animation: when the accordion mounts the sections open with animation.

Failing build:
http://pullrequest-tc.dev.wixpress.com/viewLog.html?tab=buildLog&buildTypeId=FedInfra_WixStyleReact&buildId=2621198#_state=1507,2318

Issue on Applitools: https://github.com/applitools/eyes-storybook/issues/13

This issue is to keep track of skipped tests due to this issue.

### 👀 Severity
Major

**Comment by shlomitc** [comment]
The missing feature in `eyes-storybook` to support timeouts is now available after this PR got merged https://github.com/applitools/eyes-storybook/pull/14.

This means that in order to fix this test, we should wrap the Accordion visual test and in `componentDidMount` wait for `x`ms according to `Animator`'s timeouts
This is where we use Animator in the Accordion:
https://github.com/wix/wix-style-react/blob/7a5745e55f4bd95299c62893dac4bac0b2936e07/src/Accordion/AccordionItem/AccordionItem.js#L141

and this is the CSS animations timeouts:
https://github.com/wix/wix-animations/blob/master/src/components/Animator/Animator.scss
https://github.com/wix/wix-animations/blob/master/src/components/Animator/constants/constants.js#L18

**Comment by shlomitc** [comment]
using `Snapper` now makes it easy to solve
