### ISSUE TITLE
`listItemActionBuilder` onClick is not called when inside dropdown

### ISSUE THREAD

**Issue by dorduch** [wix/wix-style-react#3438]
Example:
```
<div style={{ textAlign: 'center' }}>
  <DropdownBase
    data-hook="story-dropdown-base-uncontrolled-click"
    options={[
      { id: 0, value: 'First option' },
      listItemActionBuilder({id: 2, title: 'hi', onClick: () => alert('hllo')})
    ]}
  >
    {({ toggle, selectedOption = {} }) => {
      return (
        <TextButton
          upgrade
          skin="dark"
          suffixIcon={<ChevronDown />}
          onClick={toggle}
        >
          {selectedOption.value || 'Please choose'}
        </TextButton>
      );
    }}
  </DropdownBase>
</div>;
```

Click on the first option -> first option is selected
click on the second option

expected: 
first option is still selected, alert is shown

actual:
nothing is selected and alert is not shown

**Comment by shlomitc** [comment]
The `onSelect` callback is exposed for `DropdownBase`. that's basically what we suggest using

**Comment by dorduch** [comment]
But it's not selecting, it's clicking on an action. the selection should not be changed

**Comment by shlomitc** [comment]
You do select an option, however it is not displayed as selected in any way, which is how the item itself works

**Comment by dorduch** [comment]
please look at the attached video, after the user clicks on the action nothing is selected. I believe that is not the desired behavior 

![Untitled](https://user-images.githubusercontent.com/24411862/58022577-68d81780-7b16-11e9-97e9-dcf1cbd253b8.gif)

**Comment by shlomitc** [comment]
not sure I understand - what is the issue in the video?

**Comment by dorduch** [comment]
two issues:
1. 'onClick' is not called on `listItemActionBuilder`
2. the selected value of the dropdown is changed, even though `listItemAction` has no value - since it's an action

**Comment by mosheKerbel** [comment]
thanks dor
it is indeed not working as expected.
1. onClick - i think we should avoid using it when using `<dropdownLayout>` & `<dropdownBase>`.
because of accesibility - pressing Enter would select them but no trigger onClick. 
We should be consistent, so only use onSelect.
in my opinion we should remove the `onClick` support from `listItemAction`

2. 

> the selected value of the dropdown is changed, even though listItemAction has no value - since it's an action

We need to fix it. It happens because the value is not a string but a function, which fails on the comparion of setting/getting the selected item.

**Comment by dorduch** [comment]
Let me suggest a fix:

currently, the builder is defined as follows: 
```javascript
export const listItemActionBuilder = ({
  title,
  prefixIcon,
  onClick,
  id,
  disabled,
  skin,
  size,
}) => ({
  id,
  disabled,
  overrideStyle: true,
  value: props => (
    <ListItemAction
      {...props}
      onClick={onClick}
      title={title}
      prefixIcon={prefixIcon}
      skin={skin}
      size={size}
    />
  ),
});
```


we can change it to this:
```javascript
export const listItemActionBuilder = ({
  title,
  prefixIcon,
  onClick,
  id,
  disabled,
  skin,
  size,
}) => ({
  id,
  disabled: true,
  overrideStyle: true,
  value: props => (
    <ListItemAction
      {...props}
      disabled={disabled}
      onClick={onClick}
      title={title}
      prefixIcon={prefixIcon}
      skin={skin}
      size={size}
    />
  ),
});
```

specifically, pass `disabled: true` for the generated option (in order to prevent it from being selected), and pass the given `disabled` prop as a prop for `<ListItemAction>` component

**Comment by mosheKerbel** [comment]
2. Looking at it again:

> the selected value of the dropdown is changed, even though listItemAction has no value - since it's an action

I think the selected item should be changed, we can not distinguish between an action and an item, all of them have to be selectable items, it would be confusing otherwise.

And about a fix, there's actually nothing to fix in the component because this example is using render props:
`    {({ toggle, selectedOption = {} }) => {
      return (
        <TextButton
          upgrade
          skin="dark"
          suffixIcon={<ChevronDown />}
          onClick={toggle}
        >
          {selectedOption.value || 'Please choose'}
        </TextButton>
      );
    }}`

instead of checking `selectedOption.value`, in this case we should find the value by going over the options & selectedOption id.

**Comment by mosheKerbel** [comment]
I wrote my last comment before i saw your fix suggestion
anyways, as i said i do think it should be selected.

**Comment by mosheKerbel** [comment]
To sum up - dropdown base support selection, not clicks.
New popover menu which is soon to be released support clicks and not selection, maybe this is what you were looking for when. Will let you know once it is out.
