### ISSUE TITLE
<PageHeader/> - testkit import docs are incorrect

### ISSUE THREAD

**Issue by adicicurel** [wix/wix-style-react#3490]
# Documentation Issue

### 🔦 Scope

Relevant Page URL: https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=PageHeader&full=0&addons=0&stories=1&panelRight=0

### 💁 Explanation

Test references is page.HeaderTestkitFactory the 'dot' should be removed from properties in the doc.

...

### Expected Docs 

...

### 👀 Severity

- [ ] Major
- [ ] Low

**Comment by shlomitc** [comment]
The examples are generated automatically and read the `dispalyName` of the component.
It might be possible to rename it, however, it will screw probably the playground displayName.

**Comment by shlomitc** [comment]
@argshook - I thought that recent upgrades will fix this issue, but now looks like the `PageHeader` driver is not displayed. can you take a look?

**Comment by argshook** [comment]
Bug mentioned originally in this issue is no longer apparent, testkit tables no longer show the dot.

However, this issue outlines other issues :)
those issues are part of testkit source parser and are now reported here:
https://github.com/wix/react-autodocs-utils/issues/20
https://github.com/wix/react-autodocs-utils/issues/19

thus, closing this one. Please reopen if becomes relevant
