### ISSUE TITLE
UniDriver fails 'document not defined'

### ISSUE THREAD

**Issue by yaarams** [wix/wix-style-react#3494]
# 🐛 Bug Report

tried to use (in yoshi project) :
const testkit = await iconButtonTestkitFactory({
  dataHook: 'myDataHook',
  page,
});
got:

  ● Test suite failed to run

    ReferenceError: document is not defined

      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:944:27
      at Object.<anonymous> (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1283:5)
      at Object.<anonymous> (node_modules/react-dom/test-utils.js:6:20)
      at Object.<anonymous> (node_modules/wix-ui-core/test/utils/unidriver/ReactBase.ts:1:1)

### 🏗 Relevant Components

...

### 😯 Current Behavior

...

### 🤔 Expected Behavior

...

### 👣 Steps to Reproduce

  - **WSR version**: `...`
  - **Yoshi version**: `...`

### 👀 Severity

- Critical / Major / Low

**Comment by mosheKerbel** [comment]
opened an issue to Yoshi about it
https://github.com/wix/yoshi/issues/1386

**Comment by TalZa1810** [comment]
@shlomitc FYI

**Comment by shlomitc** [comment]
are we sure this is a `yoshi` issue? it looks to me like a completely `wix-style-react` thing.
why is `document` being referenced when talking about a puppeteer test?

**Comment by mosheKerbel** [comment]
We found out that [testkit/puppeteer.js](https://github.com/wix/wix-style-react/blob/f748397d58244195308a85ce033cd57385955871/testkit/puppeteer.js) contains imports of bad UniDrivers that cases it. 
For example - importing a UniDriver that is using a vanillaFactory which is using 'document'.

How to tackle this?
1. Comment/Uncomment imports in order to create a list of the bad unidrivers.
2. Go over each driver and fix it.

**Comment by shlomitc** [comment]
Great. Let’s tackle this one next week and add a runtime test to make sure it wont happen next time accidentally

**Comment by shlomitc** [comment]
@yaarams - hey, it looks like it's an issue of `react-dom@16.8.0`. try upgrading to `react-dom@16.8.6` or `react-dom@16.7.0` and it should be solved.

Please reopen if the issue continues. thanks!
