### ISSUE TITLE
<InputArea hasCounter maxLength={3} /> Counter is not updated when value changes not on keyDown

### ISSUE THREAD

**Issue by Shaniko** [wix/wix-style-react#3709]
<InputArea hasCounter maxLength={3} /> 

Counter is not updated when value changes (not on keyDown)
(for example, on paste )

# 🐛 Bug Report

### 🏗 Relevant Components

...

### 😯 Current Behavior

...

### 🤔 Expected Behavior

...

### 👣 Steps to Reproduce

  - **WSR version**: `...`
  - **Yoshi version**: `...`

### 👀 Severity

- Critical / Major / Low

**Comment by shlomitc** [comment]
I suggest using `FormField`'s counter capabilities instead of the built-in counter of the `InputArea`. it is much more flexible and controlled,:
```jsx
<FormField label="Label">
  {({ setCharactersLeft }) => (
    <InputArea
      onChange={event => setCharactersLeft(100 - event.target.value.length)}
    />
  )}
</FormField>
```
http://localhost:6006/?selectedKind=Components&selectedStory=FormField&full=0&addons=0&stories=1&panelRight=0

if it still doesn't work, please re-open the issue
