### ISSUE TITLE
<ImageViewer/> - remove bg color

### ISSUE THREAD

**Issue by wuwa** [wix/wix-style-react#3764]
# 🐛 Bug Report

### 🏗 Relevant Components

<ImageViewer/>

...

### 😯 Current Behavior

when uploading semi-transparent png - bg should be transparent (not blue).

...

### 🤔 Expected Behavior

change bg color to transparent after image loads (so it won't flicker)

...

### 👣 Steps to Reproduce

`<ImageViewer imageUrl="https://onlinepngtools.com/images/examples-onlinepngtools/palm-fronds-and-sky.png"/>`

  - **WSR version**: `...`
  - **Yoshi version**: `...`

### 👀 Severity

- low - needed for oneapp product

**Comment by gilmeir** [comment]
#3899 

Existing behaviour of selecting an image and having it replaces:
https://www.screencast.com/t/mcoE02X2qcEi
Image "flickers" since `AddItem` gets replaced by an `img` which takes a moment to load.

The new behaviour will be to wait for the image to load before switching `AddItem` with the `img`:
https://www.screencast.com/t/P438prk4kh

The issue is the refresh behaviour.
What do we render after the user hits the refresh button?

**Comment by gilmeir** [comment]
#3899

**Comment by gilmeir** [comment]
This feature includes a few more features as for UX request (zilvinas):
* Rendering a loader on top of an overlay while an image is loading
* When loading an image show the previous one (if there was another image before) until the image loads

Order of elements from back to front: loader on top, then overlay, then previous image.
