### ISSUE TITLE
Dependencies: `jscodeshift` produces deprecation warning for project that depends on wix-style-react

### ISSUE THREAD

**Issue by sidoruk-sv** [wix/wix-style-react#3864]
# ✨ Feature Request

### 🔦 Scope

For now, when installing the project with the dependency of `wix-style-react` user will get deprecation warning about `babel-preset-es2015`:

> npm WARN deprecated babel-preset-es2015@6.24.1: :raised_hands:  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!

### 💁 Explanation

Deprecation warning about `babel-preset-es2015` comes from `jscodeshift` (that is a `dependency` of `wix-style-react`). 
As @argshook described, `jscodeshift` is used in `wix-style-react` for **internal** stuff only.

### 🐾 Possible solution

To eliminate that deprecation warning, @argshook suggest:
- ditch that dependency;
- or at least move it to devDependencies.

### 👀 Severity

- Low

**Comment by argshook** [comment]
`jscodeshift` is currently used for:

1. `migrate-to-icons-v2` - a command registered in `bin`
2. `npm run make-async-spec` - script for internal specs manipulation (part of unidriverification (a.k.a u16n) effort)

---

1. `migrate-to-icons-v2` was used to migrate icons since during migration from
wix-style-react@4 to wix-style-react@5. It should no longer be dragged in
wix-style-react@6 or future.

2. `npm run make-async-spec` is sparringly used for internal `.spec.js` files migration to
support unidrivers. It does not require `jscodeshift` to be as `dep`, it could be as `devDep`

So, if we agree that `migrate-to-icons-v2` can be ditched, `jscodeshift` could easily become `devDep`

@shlomitc fyi, that could be a non critical but easy infra task

**Comment by shlomitc** [comment]
yes, `migrate-to-icons-v2` can be removed from this version - v6 (icons change was introduced in v4).
in general, I think that codemods can be created in a separate package (under `wix-ui`).

For example, Storybook's [migration guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md) point to the relevant [codemods](https://github.com/storybookjs/storybook/tree/next/lib/codemod) and requires the installation of both:
`yarn add jscodeshift @storybook/codemod --dev`

**Comment by argshook** [comment]
> in general, I think that codemods can be created in a separate package (under wix-ui).

i think you're saying `wix-ui-framework` :)

**Comment by shlomitc** [comment]
Actually no, `wix-ui-framework` comes to serve the different component libraries and should not be installed by the end consumers.

**Comment by ofirdagan** [comment]
you all agree that it can be moved to dev-dep or removed so let's do it 😂
meanwhile our builds are broken
