### ISSUE TITLE
auto generated testkits refactor (to be ignored in git)

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-style-react#3901]
Even though they are created automatically, we get conflicts in PRs of new components  like in here:
![image](https://user-images.githubusercontent.com/7388217/62602124-ab321900-b8fb-11e9-9310-1981c370b733.png)

Proposed solution:
1. Create the files automatically on each build and make them override the old ones.
2. Remove it from the components generation.
3. Git ignore on these files.
@argshook

**Comment by argshook** [comment]
> 1. Create the files automatically on each build and make them override the old ones.

this is done right now in `prebuild` script

> 2. Remove it from the components generation.

once component is generated, `npm run update` is invoked which adds
entries to testkit exports. In future it will do a lot more.

i'm able to split `npm run upate` from testkit exports but don't think
it's worth the effort, because point 3 below

> 3. Git ignore on these files.

that's the goal, those file are not needed to be part of git. It's
possible to do it now, but without enough tests that make sure generated
files are ok, i really don't want to do it.

All those tests will eventually be done by `wuf audit` which is my
current goal.

---

so, for now i'd argue it's ok to live a little with few conflicts until
`wuf` is capable of checking it.

Unless it's super frequent and annoying? Then i'd think of something.

**Comment by mosheKerbel** [comment]
> Unless it's super frequent and annoying? Then i'd think of something.

i'm guessing we run into it when creating **new** components, so it's not too frequent.

**Comment by EgoziE** [comment]
done
