### ISSUE TITLE
<Stepper/> ellipsis appear even when not needed in safari

### ISSUE THREAD

**Issue by adimorwix** [wix/wix-style-react#3914]
# 🐛 Bug Report

### 👣 Steps to Reproduce - open the stepper in a storybook in safari and update the text

  - **WSR version**: ` 6.46`
  - **Yoshi version**: `...`

**Comment by TalZa1810** [comment]
Hi @mosheKerbel ,
This happens only in Safari. On Chrome & Firefox it works fine. 
![rfgg](https://user-images.githubusercontent.com/24567980/62709969-1e708380-b9ff-11e9-9fd4-e782124243c8.png)

When changing the `width` calc to `calc(100% - 30px - 11px)` it seems to resolve the issue.
WDYT?

**Comment by mosheKerbel** [comment]
the px is coming from [here](https://github.com/wix/wix-style-react/blob/96945a4fc7d0bfe416533f8c1cfc127753ad959f/src/Stepper/Step/StepCircle/StepCircle.st.css#L13)
need to change it to 11px like u suggest and test it in chrome, ff, safari and edge

**Comment by EgoziE** [comment]
After some further investigation, I reached the following conclusion:
The css function `calc` is implemented differently in Safari and Chrome regarding `pixel rounding`.
Therefore the while text width in Chrome was 114.76, Safari rounded to 114.00 and showing ellipsis.

I changed the css property to be `min-width` instead, and with the max-width: 100% of `popoverElement`, the bug is fixed and the component works as intended.
