### ISSUE TITLE
Storybook code examples for easy copy-paste

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-style-react#3925]
Current state:
Examples can not be copy-paste as they are, into an external app and work.
Some examples contain "artificial" import declaration (to help the user) and some not.
Artificial because the import does not actually happen, so it may contain typos that will explode once the user run the example in his own app.

Icons - are used with the `icons.` preifix -> `<Icon.ChevronRight/>` but this code of course does not run out of the examples scope.

Desired behaviour:
Components examples could be copy-paste into an app and run without any preliminary  touch by the consumer.

@argshook @shlomitc

**Comment by shlomitc** [comment]
**Ideal situation**:
We write our code examples like real code - linted, interpreted and compiled with all of its imports.

**Currently**:
We separate the **scope** (imports) from the code, causing us to make the syntactic imports or the icon grouping.

**Suggested solutions**:
Write real code and create the scope during runtime by mapping the import statements to the right folders

Any other ideas or suggestions?

**Comment by mykas** [comment]
But do we really need to write examples with imports?  I understand the concern that we have some complex components that import multiple components, but maybe this would actually clutter our examples. 

I actually remember us running away from big bloated examples to small feature only showcases like we do now in our ux stories. Personally I think that works perfectly. 

Lets imagine how are users would really use it. Are we expecting that:
1. User creates a blank file
2. User wants to copy the whole component example wrapped in react component with all the imports?

Or:
1. User has a slot in his codebase where he would like to use it. 
2. Copy's the snippet and injects it.
3. Finds the import example and injects it too. 

Both cases possible because we have Page component examples of usage with DataTable etc.

**Comment by mykas** [comment]
But what is the real issue here? Are we having users complaining that they can't find imports? The case with Icons ok its a problem because or duplicate names but this is a different issue :)

**Comment by mykas** [comment]
What if we would have clean examples but user would have a "copy with imports" button. That would definetely help those users who don't know the paths.

**Comment by EgoziE** [comment]
Moved to Jira - closing
