### ISSUE TITLE
MessageBoxFunctionalLayout - corner isn't round when maxHeight with scrolling + hideFooter are applied

### ISSUE THREAD

**Issue by liorcode** [wix/wix-style-react#4088]
# 🐛 Bug Report

### 🏗 Relevant Components

`<MessageBoxFunctionalLayout />`

### 😯 Current Behavior

When `MessageBoxFunctionalLayout` has a maxHeight, the bottom-right corner (the one with the scrollbar) is not round.

### 🤔 Expected Behavior

All corners should be round, even with scrolling.

### 👣 Steps to Reproduce

Create a modal with MessageBoxFunctionalLayout and props hideFooter=true, maxHeight=400, then add content above 400px so scrolling would be created.
Example:
https://codesandbox.io/s/wix-style-react-id2sd

  - **WSR version**: `6.54.2`
  - **Yoshi version**: `4.13.0`

### 👀 Severity

Low

### Suggestion:
This can probably be solved easily by simply applying `overflow: hidden` to the `MessageBoxFunctionalLayout__content` class.

**Comment by shlomitc** [comment]
I don't think that setting `overflow:hidden` is the right solution. It might solve the issue but will cause other issues (dropdown opening for example).
Instead, I suggest just applying round corners for the scrollbar.
![image](https://user-images.githubusercontent.com/6093192/64848463-eec62400-d619-11e9-9d83-dd0ea15d9079.png)

I'm not sure it should be the default behavior because it is used also in other containers, but fixing this area make more sense in my opinion

**Comment by liorcode** [comment]
didn't think about dropdowns, guess you're right
so using webkit-scrollbar could work also i guess, but only for webkit browsers.
anyway, i'll be happy with what ever fix you decide on:)

**Comment by shlomitc** [comment]
It is already applying only to webkit scrollbar so I'm not too worried.

Anyway, this is on low priority, so PRs are welcome

**Comment by EgoziE** [comment]
Component is deprecated - closing
