### ISSUE TITLE
Add <MarketingCard/> Component

### ISSUE THREAD

**Issue by LittleTal** [wix/wix-style-react#4213]
# ✨ Feature Request

### 🔦 Scope

New component <MarketingCard/>

...

### 💁 Explanation

MarketingCard is a layout component - should be located as 12.9
Link to Zeplin [spec](https://zpl.io/bAWzgMo)

...

### 🐾 Possible solution 

Link to Zeplin [spec](https://zpl.io/bAWzgMo)
![image](https://user-images.githubusercontent.com/23282301/66304587-42b8e580-e906-11e9-97cc-8b3cd11b978e.png)
![image](https://user-images.githubusercontent.com/23282301/66304596-49475d00-e906-11e9-841f-e0e0a0096872.png)

...

### 👀 Severity

Low

**Comment by milkyfruit** [comment]
@LittleTal this issue was resolved developing <`MarketingLayout/>` component:
https://wix-style-react.now.sh/?selectedKind=Components&selectedStory=MarketingLayout&full=0&addons=0&stories=1&panelRight=0&activeTab=Description

However, I'm leaving this issue open, because component's specs differ from actual component.

**Comment by milkyfruit** [comment]
[design spec issue](https://app.zeplin.io/project/5c8f6f1f9f489505cac756dc/screen/5d653b94dc6f4e9be5faf105?did=5de9088793326f8a08efe2be) is resolved.
- Image area must scale proportionally
- Number of occupied columns  is defined by `size` prop.

This is video example:
https://gyazo.com/9b8cc9b313641cc31ecb92eaa99e033e

**Comment by EgoziE** [comment]
Moved to Jira - https://jira.wixpress.com/browse/DSM-77
