### ISSUE TITLE
Allow change textAlign for status message 

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-style-react#4437]
# ✨ Feature Request

### 🔦 Scope

`<Input/>` doesn't allow control properties for `statusMessage` (`<Tooltip />`. 

### 💁 Explanation

Our design: 
![image](https://user-images.githubusercontent.com/8848858/68019658-15f9b300-fca5-11e9-9f41-267e085882c8.png)

We don't know how to achieve this design with current `<Input />` implementation.

### 🐾 Possible solution 

1. Change our design with alignment to center
2. Allow to control `<Tooltip />` props.
3. Fixing #4436 will automatically fix this issue

### 👀 Severity

- Low

**Comment by rudnitskih** [comment]
@mykas I think this is a bug according to design system - https://app.zeplin.io/project/5c8f6f1f9f489505cac756dc/screen/5c90f6ab3754f40dd0464ff2

**Comment by rudnitskih** [comment]
Can we fix it in 7.x.x branch or we should for WSR 8?

**Comment by mykas** [comment]
It is a bug! I will do a pr to fix this.

**Comment by rudnitskih** [comment]
Any updates?

**Comment by nitayneeman** [comment]
@mykas I just wonder how did you planned to fix this issue because there are two options:

1. Exposing a prop that allows customizing the `statusMessage` tooltip
2. Changing the default value of `textAlign` for the tooltip to `start` (as described here -> https://github.com/wix/wix-style-react/issues/4436)

I really prefer the second option, but it's sort of a visual breaking change (or might it still look centered for regular text length and affects only a very short text?).

**Comment by mykas** [comment]
Hey @nitayneeman so your concern make sense, but I've talked with Domas and he said that mostly it should be with `start` position at all times so it make sense to align everybody because it is kind of how design systems wants it to be.

**Comment by nitayneeman** [comment]
Fixed as part of https://github.com/wix/wix-style-react/pull/4813, closing.

**Comment by rudnitskih** [comment]
Thanks guys!
