### ISSUE TITLE
<FloatingHelper> missing docs for enzyme testkit

### ISSUE THREAD

**Issue by marik22312** [wix/wix-style-react#4635]
# Documentation Issue

### 🔦 Scope

Relevant Page URL: https://wix-style-react.now.sh/?activeTab=Testkit&path=%2Fstory%2Fcomponents-api-components--floatinghelper

### 💁 Explanation

Missing enzyme testkit docs

### 👀 Severity

- [X] Low

**Comment by shlomitc** [comment]
I see an issue that prevents this unidriver from appearing in the testkit API, but that's not what causes the enzyme example to not appear.

I actually don't see `enzyme` testkits at all in other components testkits page
@argshook - is this intentional? I remember we had a talk about this but I don't remember we ditched enzyme from the docs.

**Comment by argshook** [comment]
we don't have a separate section for enzyme. `.driver.js` testkits are considered `vanilla` or `ReactTestUtils` testkits and `.uni.driver.js` are unidriver, which can also work with enzyme.

the `ReactTestUtils` table is the same api that should work with enzyme too, it's coming from `.driver.js` files, which were used also in enzyme, before unidriver became a thing

**Comment by shlomitc** [comment]
ok, so it looks like something that we should explain better.
The example shows how to import only from the vanilla testkits (`import { floatingHelperTestkitFactory } from 'wix-style-react/dist/testkit';`), so maybe in the case of both unidriver and sync driver it should show also the enzyme import.

even renaming "ReactTestUtils Testkit" to - "React Testkit" and show both options, while in the "Unidriver" show the supported platforms

**Comment by EgoziE** [comment]
Docs updated
