### ISSUE TITLE
Enable sticky inside a modal

### ISSUE THREAD

**Issue by drorl-wix** [wix/wix-style-react#4895]
# ✨ Feature Request
Today, the only way to get sticky title and toolbar of table is by using <Page.Sticky/>.
Sometime we want to use table inside of modal which doesn't have its own sticky complement.

For example:
https://app.zeplin.io/project/5d775f31683e59b8bee6443a/screen/5d8e3d74651fef170963b217

### 🔦 Scope
As I see it, we will need to add a Sticky ability for modal.

**Comment by shlomitc** [comment]
The most simple solution will be wrapping the sticky content with:
`<div style={{position: 'sticky', top: 0, zIndex: 1}}/>`

So whatever logic you have with `Page.Sticky` just replace it with this `div`.

@milkyfruit - can you think of other use cases of sticky elements inside modals? I want to understand if a sticky element is a behavior of the modal.

![image](https://user-images.githubusercontent.com/6093192/72758895-c14b4180-3bdc-11ea-93c4-0c30bf2695fd.png)

**Comment by milkyfruit** [comment]
The future modal will have a sticky header that will support subheader too: https://zpl.io/VxXBk4x
I have no real use cases, but future users might insert avatar, wizard stepper or breadcrumbs inside of it too.

**Comment by drorl-wix** [comment]
@shlomitc thanks this is what we did :)

**Comment by EgoziE** [comment]
@drorl-wix Did you manage? Can this issue be closed?

**Comment by drorl-wix** [comment]
Yep we did, I opened this issue due to Nitay's request after he helped me...

**Comment by nitayneeman** [comment]
> The future modal will have a sticky header that will support subheader too: https://zpl.io/VxXBk4x
> I have no real use cases, but future users might insert avatar, wizard stepper or breadcrumbs inside of it too.

I differentiate between two cases: 
1. Sticking stuff of the **modal header**, such as title and subtitle (both could be a custom node)
2. Sticking stuff **in addition** to the modal header - sort of a sticky spot for custom nodes below the header

Questions:

1. Do we know if at this point the custom nodes (avatar, stepper, breadcrumbs) are going to be part of the header itself or additionally below that? 
2. How often the Table is integrated inside modals? In this case, does it mean that Table's header is always supposed to be sticky? 

I'm asking because for Page we do suggest a proper way to allow the stickiness - so maybe we'd like to apply the same approach for modals as well (depending on the answers)

**Comment by milkyfruit** [comment]
@nitayneeman 
Avatar could be part of the header, for stepper and breadcrumbs I'm not sure, can be both.
All my mentioned scenarios are theoretical and they are edge cases. I guess, might happen once a year.
When "Table in modal" is used I think I know only 3-4 cases.

**Comment by nitayneeman** [comment]
Closing for now, until we'll have additional well-defined use cases
