### ISSUE TITLE
<RichTextInputArea /> - on input focus empty value becomes <p></br></p>

### ISSUE THREAD

**Issue by frontned** [wix/wix-style-react#4902]
# 🐛 Bug Report

### 🏗 Relevant Components

<RichTextInputArea />

### 😯 Current Behavior

My use-case is that we have a redux-form, and two disabled buttons: Cancel and Save. RichTextInputArea receives initialValue, for example - "" (empty string).
When the input is clicked, the value becomes - '<p><br/></p>', that makes the buttons enabled, since the value changed, but no changes are visible to the user.

### 🤔 Expected Behavior

If the value is empty on input focus it should not become - '<p><br></p>'

### 👣 Steps to Reproduce

  - **WSR version**: `6.58.0`
  - **Yoshi version**: `4.28.5`

### 👀 Severity

Low

**Comment by nitayneeman** [comment]
The problem is that empty lines are converted to `<p><br></p>` (when they should be `<p></p>` or just `<br>`). This happens because of a third-party we use under the hood (which seems to be not configurable for this part):
https://github.com/wix/wix-style-react/blob/master/src/RichTextInputArea/EditorUtilities.js#L132

This is the default behavior that was defined by the library. I also found a PR that fixes the problem but eventually was closed without merging for a reason:
https://github.com/sstur/draft-js-utils/pull/84

Not ideal, but you can handle that on your side as a workaround:
```jsx
<RichTextInputArea
 initialValue="<p>a</p><p><br></p>"
 onChange={value => console.log(value.replace(/<p><br>/g, "<p>"))}
 />
```
