### ISSUE TITLE
ellipsis inside dropdownBase don't work

### ISSUE THREAD

**Issue by marik22312** [wix/wix-style-react#5277]
# 🐛 Bug Report

### 🏗 Relevant Components

`<Dropdown/>`

### 😯 Current Behavior

when having components with ellipsis (Text, FormField) as a trigger for a dropdown, seems that the ellipsis don't work at all

### 🤔 Expected Behavior
The text should be hidden with ellipsis, a tooltip should be displayed on hover.

### 👣 Steps to Reproduce
```javascript
  <DropdownBase
    dynamicWidth
    appendTo="window"
    zIndex={5500}
    options={this.renderFieldTagsOptions()}
    onSelect={tag => this.handleSelectTagClick(tag.id)}
    open={this.state.isOpen}
    onClickOutside={() => this.setState({ isOpen: false })}
   >
    <TextButton
       placement="top"
       skin="dark"
    >
      <FormField
		label="very long test text"
      />
     </TextButton>
   </DropdownBase>
```

  - **WSR version**: `7.48`
  - **Yoshi version**: `4.1`

### 👀 Severity

- Critical - it's blocking a feature release.

**Comment by mosheKerbel** [comment]
To refine the problem - textButton has no ellipsis support. Putting inside of it `formField` or `text` still won't help.
@mykas as i understand there's a plan to add support for `ellipsis` to `TextButton`?
Anyways, here's an exact example to reproduce in the playground:
```jsx
<Box width="150px" border="1px solid black">
  <DropdownBase
    data-hook="story-dropdown-base-uncontrolled-click"
    options={[
      { id: 0, value: 'First option' },
      { id: 1, value: 'Second option' },
      { id: 2, value: 'Third option' },
      { id: 3, value: 'Fourth option' },
      { id: 4, value: 'Fifth option' },
      { id: 5, value: 'Sixth option' },
    ]}
  >
    {({ toggle, selectedOption = {} }) => {
      return (
        <TextButton
          skin="dark"
          suffixIcon={<Icons.ChevronDown />}
          onClick={toggle}
          dataHook={'drop-down-opener'}
        >
          {selectedOption.value || 'Please choose an option'}
        </TextButton>
      );
    }}
  </DropdownBase>
</Box>;
```

**Comment by mykas** [comment]
Hi, currently we have an issue with this kind of approach in getting the ellipsis working deep in nested wrappers when only the parent component defines the width. For this to work we need to develop our ellipsis solution in different way. 

One way to make this work is to construct TextButton functionality with Text component like this. 
```jsx
<Box width="150px"> 
<DropdownBase
    data-hook="story-dropdown-base-uncontrolled-click"
    options={[
      { id: 0, value: 'First option' },
      { id: 1, value: 'Second option' },
      { id: 2, value: 'Third option' },
      { id: 3, value: 'Fourth option' },
      { id: 4, value: 'Fifth option' },
      { id: 5, value: 'Sixth option' },
    ]}
  >
    {({ toggle, selectedOption = {} }) => {
      return (
    <div onClick={toggle}>
      <Box >
        <Text
          tagName="a"
          skin="dark"
          ellipsis={true}
        >
          {selectedOption.value || 'Please choose an option'}
        </Text>
         <Icons.ChevronDown />
      </Box>
   </div>  
      );
    }}
  </DropdownBase>
</Box>
```
But additional stuff needs to be done on DropdownBase element which has `inline-block` by default that makes it ignore the parent width. 

@shlomitc what do you think? Should we expose some prop on DropdownBase to support making the element flex to 100% of its parent container?

**Comment by shlomitc** [comment]
I wanted to understand the problem better so I did some research, these are not the solutions but rather how to focus on the root cause.

1. Let's just narrow down the problem with a simple example, so now we can see the first issue clearly.

```jsx
<>
  {/* Doesn't work */}
  <div style={{width:"150px", border:"1px solid black"}}>
    <div style={{display: 'inline-block'}}>
      <Text ellipsis>Hello Worold hello world</Text>
    </div>
  </div>

  {/* Works */}  
  <div style={{width:"150px", border:"1px solid black"}}>
    <div>
      <Text ellipsis>Hello Worold hello world</Text>
    </div>
  </div>
</>
```

![image](https://user-images.githubusercontent.com/6093192/77832632-8b7c8900-7148-11ea-8e5f-ab8ea74f6575.png)

2. Now let's add just a bit more complex example that uses `DropdownBase` (and behind the scenes `Popover`). It will apply `inline-block` to the Popover trigger element, and thus will not show the ellipsis (I removed `Box` because it was a flex container so it wouldn't work that way)

```jsx
<div style={{width:"150px", border:"1px solid black"}}>
  <DropdownBase
    options={[
      { id: 0, value: 'First option' },
      { id: 1, value: 'Second option' },
      { id: 2, value: 'Third option' },
      { id: 3, value: 'Fourth option' },
      { id: 4, value: 'Fifth option' },
      { id: 5, value: 'Sixth option' },
    ]}
  >
    {({ toggle, selectedOption = {} }) => {
      return (
        <Text ellipsis onClick={toggle}>
          {selectedOption.value || 'Please choose an option'}
        </Text>
      );
    }}
  </DropdownBase>
</div>
```
![image](https://user-images.githubusercontent.com/6093192/77832774-76ecc080-7149-11ea-9330-edbb818ca9c8.png)

3. If we just add replace `inline-block` with `block`, everything looks good and the Dropdown even opens, however, the `Tootlip` doesn't show up.

![image](https://user-images.githubusercontent.com/6093192/77832769-6fc5b280-7149-11ea-98f8-29f83d462585.png)
![image](https://user-images.githubusercontent.com/6093192/77832813-c4692d80-7149-11ea-91db-e0cee74e9163.png)

4. Narrowing down to `Popover` in order to understand that something blocks the event from triggering (again, overriding with `display:block`)

```jsx
<div style={{width:"150px", border:"1px solid black"}}>
  <Popover>
    <Popover.Element>
      <Text ellipsis> Please choose an option</Text>
      </Popover.Element>
  </Popover>
</div>
```

### Conclusion so far:
1. The `display: inline-block` was set in `wix-ui-core` [Popover's css](https://github.com/wix/wix-ui/blob/master/packages/wix-ui-core/src/components/popover/Popover.st.css#L26) because of measurements issue. This was a long time ago and probably will require some investigation.
 
2. Regarding tooltip that doesn't appear, even when `display: block` is set, that's a mystery of `popper.js` which needs to be investigated further.

We will add this investigation to work in one of our next iterations

**Comment by mykas** [comment]
Hey @shlomitc , thanks for the detailed explanation. Before I'll paste my explanation here I would like to point that point 3 actually works well with Tooltip. The tooltip did not appear because we have some weird bug with storybook iframe in development only. Just try to resize the screen and it will start to work.


![storybook](https://user-images.githubusercontent.com/8919190/78257301-597d7500-7502-11ea-96f1-4d79a8b937a1.gif)

**Comment by mykas** [comment]
### The real reason why Popover implementation went for inline-block instead of block or inline

Lets see by example on whats happening when we change the display value.

## `display: block`

Block elements are made to fill all the available width by default and are thus on their own line rather than flowing inline. This is good for things like paragraphs, but sometimes you want shorter lines so it is possible to adjust the width for block elements.

1. force a line break after the block element
3. acquires full-width if width not defined

#### Change
<img width="1666" alt="Screenshot 2020-04-02 at 13 27 10" src="https://user-images.githubusercontent.com/8919190/78239110-0269a700-74e6-11ea-8d35-27b3afd028a0.png">

#### Mouse trigger
![Block](https://user-images.githubusercontent.com/8919190/78239575-891e8400-74e6-11ea-8f57-79b921be7145.gif)

#### Container visually
<img width="559" alt="Screenshot 2020-04-02 at 14 39 57" src="https://user-images.githubusercontent.com/8919190/78245305-ef5bd480-74ef-11ea-8dda-516e06e1413b.png">

#### Reaction to parent container width (width=200px)

<img width="586" alt="Screenshot 2020-04-02 at 15 49 39" src="https://user-images.githubusercontent.com/8919190/78251295-cdffe600-74f9-11ea-9ba2-60e39b64e434.png">

![reaction](https://user-images.githubusercontent.com/8919190/78251374-ec65e180-74f9-11ea-94e8-f0aab7bfaeae.gif)


#### Thoughts

This is case which does not work well when our trigger elements are inline-block based like Buttons.  This is because the root container acquires full-width if width not defined.
 
##### Pros
1. Reacts to parent width.
2. Takes the full width available. 
3. Lets the trigger element of popover flow until it fill available width.
##### Cons
1. Does not play well with trigger elements that are `inline-block` based.

This way it could benefit cases like the problem mentioned by Shlomi.

## `display:inline`

Inline elements are built for text and thus they should flow inline with the text, and only be as wide as the text they contain. Thus, you can't set the `width` of an inline element.

1. respect left & right margins and padding, but not top & bottom
2. cannot have a width and height set
3. allow other elements to sit to their left and right.

#### Change

Here we need to fix this not just for root container but also for trigger element as it is by default a block.
<img width="1668" alt="Screenshot 2020-04-02 at 14 42 49" src="https://user-images.githubusercontent.com/8919190/78245712-9c365180-74f0-11ea-901e-d3f1550bc48e.png">
<img width="1667" alt="Screenshot 2020-04-02 at 14 44 23" src="https://user-images.githubusercontent.com/8919190/78245716-9f314200-74f0-11ea-804f-ed220cb7c954.png">

#### Mouse Trigger
![inline](https://user-images.githubusercontent.com/8919190/78245852-d869b200-74f0-11ea-9f04-60f4f83ccaa8.gif)

#### Container visually

<img width="555" alt="Screenshot 2020-04-02 at 14 47 52" src="https://user-images.githubusercontent.com/8919190/78245936-fafbcb00-74f0-11ea-8a7a-20a1b75b0f71.png">

#### Thoughs

This use case I think does not fit any of our popover cases.

##### Cons
1.  Does not respect top & bottom. So in this case we see tooltip positioned directly on button content instead of button with paddings container.

## `display: inline-block`

Inline-block elements are in the middle. They flow inline like display: inline; elements, but you can set the width like display: block; elements.

#### Change

none, because this is default.

#### Mouse Trigger

as usual works best with all cases that have `inline-block` based trigger elements, but does not work well with block based elements where trigger elements take full available width of its parent. 

Like this example.
![image](https://user-images.githubusercontent.com/6093192/77832774-76ecc080-7149-11ea-9330-edbb818ca9c8.png)


### Conclusion

So we see that mostly Popover was developed in mind with inline-block based component and not with full-width taken elements. 

That means we need to develop a way to switch between: inline-block and block.

**Comment by shlomitc** [comment]
Wow this is a really great investigation! I must say I never dived into the differences, so it is super useful.

So adding a block capability sounds like a something that will solve this issue.

Regarding the iframe issue - do you mind verifying if it’s actually because of it or because inconsistent event triggering? For example a clean client project - will it work there?

Thanks!

**Comment by mykas** [comment]
Hey @marik22312 , I've just merged a solution that will work for you. 

> Just FYI this requires you to upgrade `wix-style-react` to major version 8 as this is not really a bug that we fixed, but a feature that we  support now.

Here is an example of working code:
```jsx
<Box align="center">
  <div style={{ width: '100px' }}>
    <DropdownBase
      fluid
      options={[
        { id: 0, value: 'First option' },
        { id: 1, value: 'Second option' },
        { id: 2, value: 'Third option' },
        { id: 3, value: 'Fourth option' },
        { id: 4, value: 'Fifth option' },
        { id: 5, value: 'Sixth option' },
      ]}
    >
      {({ toggle, selectedOption = {} }) => {
        return (
          <TextButton
            skin="dark"
            fluid
            suffixIcon={<Icons.ChevronDown />}
            onClick={toggle}
          >
            <Text ellipsis={true}>
              {selectedOption.value || 'Please choose'}
            </Text>
          </TextButton>
        );
      }}
    </DropdownBase>
  </div>
</Box>;
```
