### ISSUE TITLE
CustomModalLayout - content is cut

### ISSUE THREAD

**Issue by ofiratt** [wix/wix-style-react#5874]
# 🐛 Bug Report

### 😯 Current Behavior

When adding an input as the model content and focusing on the input the outline is cut at the top and bottom.

### 🤔 Expected Behavior

Outline shouldn't be cut.

### 👣 Steps to Reproduce
https://wix.slack.com/archives/C39FTGUBZ/p1598255075077500 OR
https://codesandbox.io/s/wix-style-react-forked-c3vjs?file=/src/App/index.js

**Comment by sivanharel** [comment]
When adding an input as the model content and focusing on the input the outline is cut in the top. The bug happens since the is no enough space. A suggested solution is to add padding-top to the content.
https://www.wix.com/pages/wix-style-react/?path=/story/introduction-playground--playground&snippet=28cea619-6ed7-47ac-945b-a0a294d01aff

**Comment by sivanharel** [comment]
After discussing with Domas we decided that:
When the prop "removeContentPadding" is false we should add padding-top and padding-bottom of 6px.

**Comment by shlomitc** [comment]
so `removeContentPadding` doesn't sound like a good name, since you do add padding.

**Comment by sivanharel** [comment]
"removeContentPadding" prop is already existed, at the moment it related only for the padding right and left that by default is 30px for each.

**Comment by sivanharel** [comment]
Resolved
