### ISSUE TITLE
DatePicker readOnly prop doesn't work (disable prop does)

### ISSUE THREAD

**Issue by tomer-sharon** [wix/wix-style-react#634]
In the StoryBook it says this prop should disable\enable modifying the date

It seems that this prop is propagated to ReactDatePicker component, but is not supported by it.
'disabled' prop, however, exists on ReactDatePicker and is working as expected.

**Comment by lbelinsk** [comment]
I will take a look..

**Comment by lbelinsk** [comment]
@tomer-sharon just pass disabled prop instead of readOnly. We do support it.
I will update the docs with a new story example.

ReactDatepicker support readOnly as well, but it is only for the Input,  not for the DatePicker itself. You cant type manually the date but you can select one in the date picker.
See here: 
https://github.com/Hacker0x01/react-datepicker/blob/b5f9bfd53fcd3a38eecd430ba568ce5fcc15af5a/src/datepicker.jsx#L409

disabled prop is exactly what you need: https://github.com/Hacker0x01/react-datepicker/blob/b5f9bfd53fcd3a38eecd430ba568ce5fcc15af5a/src/datepicker.jsx#L455
