### ISSUE TITLE
Cannot display custom values in Dropdown input

### ISSUE THREAD

**Issue by guybenron** [wix/wix-style-react#701]
While the dropdown option list displays any React node as is, the button part displays `[object Object]` if given anything other than a string.

Consider the following code:
```javascript
const options = [
    {id: 0, value: <div style = {{color : 'green'}}>Option 1</div>},
    {id: 1, value: <div style = {{color : 'green'}}>Option 2</div>},
];

<Dropdown selectedId={0} options={options}/>
```
Expected behavior is this:
![screen shot 2017-08-10 at 17 33 22](https://user-images.githubusercontent.com/10583243/29175686-5d73cc36-7df2-11e7-9a46-a51921e9b3b0.png)

Actual behavior is this:
![screen shot 2017-08-10 at 17 29 37](https://user-images.githubusercontent.com/10583243/29175697-673811a0-7df2-11e7-8c89-a284588c6b41.png)

**Comment by lbelinsk** [comment]
Hey @guybenron, since custom values are not predicted, we need the user to provide a valueParser function which maps option => String value.

The default function is option => option.value.

See the storybook example, last example (Custom Values in Dropdown):

https://wix.github.io/wix-style-react/?selectedKind=Core&selectedStory=Dropdown&full=0&down=0&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

Please let me know if the explanation was clear enough and that I can close this issue.
