### ISSUE TITLE
Add ability to set data hooks on dropdown items.

### ISSUE THREAD

**Issue by crownz** [wix/wix-style-react#733]
Data hooks are needed for selenium testing and would improve testkit, because selecting by an index might not always be accurate if dropdown values are dynamic.

**Comment by nirhart** [comment]
@crownz I don't think that its the right thing to do when we are using testkits, how about adding a method in the testkit that finds an item by id?

**Comment by crownz** [comment]
@nirhart Could you explain why adding an optional data hook would not be a right thing to do? It would be optional in the testkit to do actions either by position or the data hook (user preference). None of the behaviour would change and it would be a useful addition for QA engineers to have data hooks for automation or teskit users to write more specific tests.

Also did I understand correctly that you are suggesting to use option id in a similar way as data hook?

**Comment by nirhart** [comment]
You understood correctly, it will be the same for the QA engineers, each option should have a unique ID. data hook is reserved for inner implementations in wix-style-react, so I think semantically it will be wrong

**Comment by joncys** [comment]
@nirhart We're also using `data-hook`s when selecting components to feed into testkit drivers and when running QA automation tests. Would you concider it a bad practice and if so, how should we select nodes instead?

_We don't want to use classes for this since classes might change and using `#` ids is somewhat difficult, because you need to make sure they're unique, that might involve some generation which then renders selecting these nodes by QA automation scripts impossible._

**Comment by nirhart** [comment]
@joncys you right about the data-hook for selecting components, I take it back, but still, why would we want 2 different uniques for an option?

**Comment by joncys** [comment]
@nirhart Totally on board with the _no need for the two uniques_ sentiment. 👍🏻 Just wanted to clarify, where do we stand on the _"data-hook" is reserved for inner implementations in `wix-style-react`_ idea.

**Comment by crownz** [comment]
Solved #741
